[package]
name = "cargo-list-cache"
description = "Lists the files in your crate cache (${CARGO_HOME}/registry/cache/...)."
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
